// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorldBossProto.proto

package proto;

public final class WorldBossProto {
  private WorldBossProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AttackBossReq_1002001OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protoFiles.AttackBossReq_1002001}
   *
   * <pre>
   *请求攻打世界boss
   * </pre>
   */
  public static final class AttackBossReq_1002001 extends
      com.google.protobuf.GeneratedMessage
      implements AttackBossReq_1002001OrBuilder {
    // Use AttackBossReq_1002001.newBuilder() to construct.
    private AttackBossReq_1002001(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AttackBossReq_1002001(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AttackBossReq_1002001 defaultInstance;
    public static AttackBossReq_1002001 getDefaultInstance() {
      return defaultInstance;
    }

    public AttackBossReq_1002001 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AttackBossReq_1002001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.WorldBossProto.internal_static_protoFiles_AttackBossReq_1002001_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.WorldBossProto.internal_static_protoFiles_AttackBossReq_1002001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.WorldBossProto.AttackBossReq_1002001.class, proto.WorldBossProto.AttackBossReq_1002001.Builder.class);
    }

    public static com.google.protobuf.Parser<AttackBossReq_1002001> PARSER =
        new com.google.protobuf.AbstractParser<AttackBossReq_1002001>() {
      public AttackBossReq_1002001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AttackBossReq_1002001(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AttackBossReq_1002001> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.WorldBossProto.AttackBossReq_1002001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.WorldBossProto.AttackBossReq_1002001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.WorldBossProto.AttackBossReq_1002001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.AttackBossReq_1002001}
     *
     * <pre>
     *请求攻打世界boss
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.WorldBossProto.AttackBossReq_1002001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.WorldBossProto.internal_static_protoFiles_AttackBossReq_1002001_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.WorldBossProto.internal_static_protoFiles_AttackBossReq_1002001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.WorldBossProto.AttackBossReq_1002001.class, proto.WorldBossProto.AttackBossReq_1002001.Builder.class);
      }

      // Construct using proto.WorldBossProto.AttackBossReq_1002001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.WorldBossProto.internal_static_protoFiles_AttackBossReq_1002001_descriptor;
      }

      public proto.WorldBossProto.AttackBossReq_1002001 getDefaultInstanceForType() {
        return proto.WorldBossProto.AttackBossReq_1002001.getDefaultInstance();
      }

      public proto.WorldBossProto.AttackBossReq_1002001 build() {
        proto.WorldBossProto.AttackBossReq_1002001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.WorldBossProto.AttackBossReq_1002001 buildPartial() {
        proto.WorldBossProto.AttackBossReq_1002001 result = new proto.WorldBossProto.AttackBossReq_1002001(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.WorldBossProto.AttackBossReq_1002001) {
          return mergeFrom((proto.WorldBossProto.AttackBossReq_1002001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.WorldBossProto.AttackBossReq_1002001 other) {
        if (other == proto.WorldBossProto.AttackBossReq_1002001.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.WorldBossProto.AttackBossReq_1002001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.WorldBossProto.AttackBossReq_1002001) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.AttackBossReq_1002001)
    }

    static {
      defaultInstance = new AttackBossReq_1002001(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.AttackBossReq_1002001)
  }

  public interface AttackBossResp_1002001OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 leftHP = 1;
    /**
     * <code>optional int64 leftHP = 1;</code>
     *
     * <pre>
     *剩余血量
     * </pre>
     */
    boolean hasLeftHP();
    /**
     * <code>optional int64 leftHP = 1;</code>
     *
     * <pre>
     *剩余血量
     * </pre>
     */
    long getLeftHP();

    // optional int64 hurt = 2;
    /**
     * <code>optional int64 hurt = 2;</code>
     *
     * <pre>
     *累积伤害总量
     * </pre>
     */
    boolean hasHurt();
    /**
     * <code>optional int64 hurt = 2;</code>
     *
     * <pre>
     *累积伤害总量
     * </pre>
     */
    long getHurt();
  }
  /**
   * Protobuf type {@code protoFiles.AttackBossResp_1002001}
   */
  public static final class AttackBossResp_1002001 extends
      com.google.protobuf.GeneratedMessage
      implements AttackBossResp_1002001OrBuilder {
    // Use AttackBossResp_1002001.newBuilder() to construct.
    private AttackBossResp_1002001(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AttackBossResp_1002001(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AttackBossResp_1002001 defaultInstance;
    public static AttackBossResp_1002001 getDefaultInstance() {
      return defaultInstance;
    }

    public AttackBossResp_1002001 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AttackBossResp_1002001(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              leftHP_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hurt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.WorldBossProto.internal_static_protoFiles_AttackBossResp_1002001_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.WorldBossProto.internal_static_protoFiles_AttackBossResp_1002001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.WorldBossProto.AttackBossResp_1002001.class, proto.WorldBossProto.AttackBossResp_1002001.Builder.class);
    }

    public static com.google.protobuf.Parser<AttackBossResp_1002001> PARSER =
        new com.google.protobuf.AbstractParser<AttackBossResp_1002001>() {
      public AttackBossResp_1002001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AttackBossResp_1002001(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AttackBossResp_1002001> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 leftHP = 1;
    public static final int LEFTHP_FIELD_NUMBER = 1;
    private long leftHP_;
    /**
     * <code>optional int64 leftHP = 1;</code>
     *
     * <pre>
     *剩余血量
     * </pre>
     */
    public boolean hasLeftHP() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 leftHP = 1;</code>
     *
     * <pre>
     *剩余血量
     * </pre>
     */
    public long getLeftHP() {
      return leftHP_;
    }

    // optional int64 hurt = 2;
    public static final int HURT_FIELD_NUMBER = 2;
    private long hurt_;
    /**
     * <code>optional int64 hurt = 2;</code>
     *
     * <pre>
     *累积伤害总量
     * </pre>
     */
    public boolean hasHurt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 hurt = 2;</code>
     *
     * <pre>
     *累积伤害总量
     * </pre>
     */
    public long getHurt() {
      return hurt_;
    }

    private void initFields() {
      leftHP_ = 0L;
      hurt_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, leftHP_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, hurt_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, leftHP_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, hurt_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.WorldBossProto.AttackBossResp_1002001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.WorldBossProto.AttackBossResp_1002001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.WorldBossProto.AttackBossResp_1002001 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.AttackBossResp_1002001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.WorldBossProto.AttackBossResp_1002001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.WorldBossProto.internal_static_protoFiles_AttackBossResp_1002001_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.WorldBossProto.internal_static_protoFiles_AttackBossResp_1002001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.WorldBossProto.AttackBossResp_1002001.class, proto.WorldBossProto.AttackBossResp_1002001.Builder.class);
      }

      // Construct using proto.WorldBossProto.AttackBossResp_1002001.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        leftHP_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        hurt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.WorldBossProto.internal_static_protoFiles_AttackBossResp_1002001_descriptor;
      }

      public proto.WorldBossProto.AttackBossResp_1002001 getDefaultInstanceForType() {
        return proto.WorldBossProto.AttackBossResp_1002001.getDefaultInstance();
      }

      public proto.WorldBossProto.AttackBossResp_1002001 build() {
        proto.WorldBossProto.AttackBossResp_1002001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.WorldBossProto.AttackBossResp_1002001 buildPartial() {
        proto.WorldBossProto.AttackBossResp_1002001 result = new proto.WorldBossProto.AttackBossResp_1002001(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.leftHP_ = leftHP_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hurt_ = hurt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.WorldBossProto.AttackBossResp_1002001) {
          return mergeFrom((proto.WorldBossProto.AttackBossResp_1002001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.WorldBossProto.AttackBossResp_1002001 other) {
        if (other == proto.WorldBossProto.AttackBossResp_1002001.getDefaultInstance()) return this;
        if (other.hasLeftHP()) {
          setLeftHP(other.getLeftHP());
        }
        if (other.hasHurt()) {
          setHurt(other.getHurt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.WorldBossProto.AttackBossResp_1002001 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.WorldBossProto.AttackBossResp_1002001) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 leftHP = 1;
      private long leftHP_ ;
      /**
       * <code>optional int64 leftHP = 1;</code>
       *
       * <pre>
       *剩余血量
       * </pre>
       */
      public boolean hasLeftHP() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 leftHP = 1;</code>
       *
       * <pre>
       *剩余血量
       * </pre>
       */
      public long getLeftHP() {
        return leftHP_;
      }
      /**
       * <code>optional int64 leftHP = 1;</code>
       *
       * <pre>
       *剩余血量
       * </pre>
       */
      public Builder setLeftHP(long value) {
        bitField0_ |= 0x00000001;
        leftHP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 leftHP = 1;</code>
       *
       * <pre>
       *剩余血量
       * </pre>
       */
      public Builder clearLeftHP() {
        bitField0_ = (bitField0_ & ~0x00000001);
        leftHP_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 hurt = 2;
      private long hurt_ ;
      /**
       * <code>optional int64 hurt = 2;</code>
       *
       * <pre>
       *累积伤害总量
       * </pre>
       */
      public boolean hasHurt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 hurt = 2;</code>
       *
       * <pre>
       *累积伤害总量
       * </pre>
       */
      public long getHurt() {
        return hurt_;
      }
      /**
       * <code>optional int64 hurt = 2;</code>
       *
       * <pre>
       *累积伤害总量
       * </pre>
       */
      public Builder setHurt(long value) {
        bitField0_ |= 0x00000002;
        hurt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 hurt = 2;</code>
       *
       * <pre>
       *累积伤害总量
       * </pre>
       */
      public Builder clearHurt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hurt_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.AttackBossResp_1002001)
    }

    static {
      defaultInstance = new AttackBossResp_1002001(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.AttackBossResp_1002001)
  }

  public interface HurtAwardReq_1002002OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protoFiles.HurtAwardReq_1002002}
   *
   * <pre>
   *请求伤害领奖
   * </pre>
   */
  public static final class HurtAwardReq_1002002 extends
      com.google.protobuf.GeneratedMessage
      implements HurtAwardReq_1002002OrBuilder {
    // Use HurtAwardReq_1002002.newBuilder() to construct.
    private HurtAwardReq_1002002(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HurtAwardReq_1002002(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HurtAwardReq_1002002 defaultInstance;
    public static HurtAwardReq_1002002 getDefaultInstance() {
      return defaultInstance;
    }

    public HurtAwardReq_1002002 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HurtAwardReq_1002002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.WorldBossProto.internal_static_protoFiles_HurtAwardReq_1002002_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.WorldBossProto.internal_static_protoFiles_HurtAwardReq_1002002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.WorldBossProto.HurtAwardReq_1002002.class, proto.WorldBossProto.HurtAwardReq_1002002.Builder.class);
    }

    public static com.google.protobuf.Parser<HurtAwardReq_1002002> PARSER =
        new com.google.protobuf.AbstractParser<HurtAwardReq_1002002>() {
      public HurtAwardReq_1002002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HurtAwardReq_1002002(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HurtAwardReq_1002002> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.WorldBossProto.HurtAwardReq_1002002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.WorldBossProto.HurtAwardReq_1002002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.WorldBossProto.HurtAwardReq_1002002 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.HurtAwardReq_1002002}
     *
     * <pre>
     *请求伤害领奖
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.WorldBossProto.HurtAwardReq_1002002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.WorldBossProto.internal_static_protoFiles_HurtAwardReq_1002002_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.WorldBossProto.internal_static_protoFiles_HurtAwardReq_1002002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.WorldBossProto.HurtAwardReq_1002002.class, proto.WorldBossProto.HurtAwardReq_1002002.Builder.class);
      }

      // Construct using proto.WorldBossProto.HurtAwardReq_1002002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.WorldBossProto.internal_static_protoFiles_HurtAwardReq_1002002_descriptor;
      }

      public proto.WorldBossProto.HurtAwardReq_1002002 getDefaultInstanceForType() {
        return proto.WorldBossProto.HurtAwardReq_1002002.getDefaultInstance();
      }

      public proto.WorldBossProto.HurtAwardReq_1002002 build() {
        proto.WorldBossProto.HurtAwardReq_1002002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.WorldBossProto.HurtAwardReq_1002002 buildPartial() {
        proto.WorldBossProto.HurtAwardReq_1002002 result = new proto.WorldBossProto.HurtAwardReq_1002002(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.WorldBossProto.HurtAwardReq_1002002) {
          return mergeFrom((proto.WorldBossProto.HurtAwardReq_1002002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.WorldBossProto.HurtAwardReq_1002002 other) {
        if (other == proto.WorldBossProto.HurtAwardReq_1002002.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.WorldBossProto.HurtAwardReq_1002002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.WorldBossProto.HurtAwardReq_1002002) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.HurtAwardReq_1002002)
    }

    static {
      defaultInstance = new HurtAwardReq_1002002(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.HurtAwardReq_1002002)
  }

  public interface HurtAwardResp_1002002OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 ids = 1;
    /**
     * <code>repeated int32 ids = 1;</code>
     *
     * <pre>
     *已领奖项
     * </pre>
     */
    java.util.List<java.lang.Integer> getIdsList();
    /**
     * <code>repeated int32 ids = 1;</code>
     *
     * <pre>
     *已领奖项
     * </pre>
     */
    int getIdsCount();
    /**
     * <code>repeated int32 ids = 1;</code>
     *
     * <pre>
     *已领奖项
     * </pre>
     */
    int getIds(int index);

    // repeated .protoFiles.Item items = 2;
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    java.util.List<proto.RoleProto.Item> 
        getItemsList();
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    proto.RoleProto.Item getItems(int index);
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    int getItemsCount();
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    java.util.List<? extends proto.RoleProto.ItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    proto.RoleProto.ItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protoFiles.HurtAwardResp_1002002}
   */
  public static final class HurtAwardResp_1002002 extends
      com.google.protobuf.GeneratedMessage
      implements HurtAwardResp_1002002OrBuilder {
    // Use HurtAwardResp_1002002.newBuilder() to construct.
    private HurtAwardResp_1002002(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HurtAwardResp_1002002(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HurtAwardResp_1002002 defaultInstance;
    public static HurtAwardResp_1002002 getDefaultInstance() {
      return defaultInstance;
    }

    public HurtAwardResp_1002002 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HurtAwardResp_1002002(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              ids_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                ids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                ids_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                items_ = new java.util.ArrayList<proto.RoleProto.Item>();
                mutable_bitField0_ |= 0x00000002;
              }
              items_.add(input.readMessage(proto.RoleProto.Item.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = java.util.Collections.unmodifiableList(ids_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.WorldBossProto.internal_static_protoFiles_HurtAwardResp_1002002_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.WorldBossProto.internal_static_protoFiles_HurtAwardResp_1002002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.WorldBossProto.HurtAwardResp_1002002.class, proto.WorldBossProto.HurtAwardResp_1002002.Builder.class);
    }

    public static com.google.protobuf.Parser<HurtAwardResp_1002002> PARSER =
        new com.google.protobuf.AbstractParser<HurtAwardResp_1002002>() {
      public HurtAwardResp_1002002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HurtAwardResp_1002002(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HurtAwardResp_1002002> getParserForType() {
      return PARSER;
    }

    // repeated int32 ids = 1;
    public static final int IDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> ids_;
    /**
     * <code>repeated int32 ids = 1;</code>
     *
     * <pre>
     *已领奖项
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated int32 ids = 1;</code>
     *
     * <pre>
     *已领奖项
     * </pre>
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated int32 ids = 1;</code>
     *
     * <pre>
     *已领奖项
     * </pre>
     */
    public int getIds(int index) {
      return ids_.get(index);
    }

    // repeated .protoFiles.Item items = 2;
    public static final int ITEMS_FIELD_NUMBER = 2;
    private java.util.List<proto.RoleProto.Item> items_;
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    public java.util.List<proto.RoleProto.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    public java.util.List<? extends proto.RoleProto.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    public proto.RoleProto.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .protoFiles.Item items = 2;</code>
     *
     * <pre>
     *奖励物品
     * </pre>
     */
    public proto.RoleProto.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      ids_ = java.util.Collections.emptyList();
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ids_.size(); i++) {
        output.writeInt32(1, ids_.get(i));
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(ids_.get(i));
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.WorldBossProto.HurtAwardResp_1002002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.WorldBossProto.HurtAwardResp_1002002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.WorldBossProto.HurtAwardResp_1002002 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.HurtAwardResp_1002002}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.WorldBossProto.HurtAwardResp_1002002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.WorldBossProto.internal_static_protoFiles_HurtAwardResp_1002002_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.WorldBossProto.internal_static_protoFiles_HurtAwardResp_1002002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.WorldBossProto.HurtAwardResp_1002002.class, proto.WorldBossProto.HurtAwardResp_1002002.Builder.class);
      }

      // Construct using proto.WorldBossProto.HurtAwardResp_1002002.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.WorldBossProto.internal_static_protoFiles_HurtAwardResp_1002002_descriptor;
      }

      public proto.WorldBossProto.HurtAwardResp_1002002 getDefaultInstanceForType() {
        return proto.WorldBossProto.HurtAwardResp_1002002.getDefaultInstance();
      }

      public proto.WorldBossProto.HurtAwardResp_1002002 build() {
        proto.WorldBossProto.HurtAwardResp_1002002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.WorldBossProto.HurtAwardResp_1002002 buildPartial() {
        proto.WorldBossProto.HurtAwardResp_1002002 result = new proto.WorldBossProto.HurtAwardResp_1002002(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = java.util.Collections.unmodifiableList(ids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ids_ = ids_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.WorldBossProto.HurtAwardResp_1002002) {
          return mergeFrom((proto.WorldBossProto.HurtAwardResp_1002002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.WorldBossProto.HurtAwardResp_1002002 other) {
        if (other == proto.WorldBossProto.HurtAwardResp_1002002.getDefaultInstance()) return this;
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.WorldBossProto.HurtAwardResp_1002002 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.WorldBossProto.HurtAwardResp_1002002) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 ids = 1;
      private java.util.List<java.lang.Integer> ids_ = java.util.Collections.emptyList();
      private void ensureIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = new java.util.ArrayList<java.lang.Integer>(ids_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 ids = 1;</code>
       *
       * <pre>
       *已领奖项
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getIdsList() {
        return java.util.Collections.unmodifiableList(ids_);
      }
      /**
       * <code>repeated int32 ids = 1;</code>
       *
       * <pre>
       *已领奖项
       * </pre>
       */
      public int getIdsCount() {
        return ids_.size();
      }
      /**
       * <code>repeated int32 ids = 1;</code>
       *
       * <pre>
       *已领奖项
       * </pre>
       */
      public int getIds(int index) {
        return ids_.get(index);
      }
      /**
       * <code>repeated int32 ids = 1;</code>
       *
       * <pre>
       *已领奖项
       * </pre>
       */
      public Builder setIds(
          int index, int value) {
        ensureIdsIsMutable();
        ids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 1;</code>
       *
       * <pre>
       *已领奖项
       * </pre>
       */
      public Builder addIds(int value) {
        ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 1;</code>
       *
       * <pre>
       *已领奖项
       * </pre>
       */
      public Builder addAllIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdsIsMutable();
        super.addAll(values, ids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 1;</code>
       *
       * <pre>
       *已领奖项
       * </pre>
       */
      public Builder clearIds() {
        ids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated .protoFiles.Item items = 2;
      private java.util.List<proto.RoleProto.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = new java.util.ArrayList<proto.RoleProto.Item>(items_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.RoleProto.Item, proto.RoleProto.Item.Builder, proto.RoleProto.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public java.util.List<proto.RoleProto.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public proto.RoleProto.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder setItems(
          int index, proto.RoleProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder setItems(
          int index, proto.RoleProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder addItems(proto.RoleProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder addItems(
          int index, proto.RoleProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder addItems(
          proto.RoleProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder addItems(
          int index, proto.RoleProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends proto.RoleProto.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          super.addAll(values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public proto.RoleProto.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public proto.RoleProto.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public java.util.List<? extends proto.RoleProto.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public proto.RoleProto.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            proto.RoleProto.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public proto.RoleProto.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, proto.RoleProto.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .protoFiles.Item items = 2;</code>
       *
       * <pre>
       *奖励物品
       * </pre>
       */
      public java.util.List<proto.RoleProto.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.RoleProto.Item, proto.RoleProto.Item.Builder, proto.RoleProto.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.RoleProto.Item, proto.RoleProto.Item.Builder, proto.RoleProto.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.HurtAwardResp_1002002)
    }

    static {
      defaultInstance = new HurtAwardResp_1002002(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.HurtAwardResp_1002002)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_AttackBossReq_1002001_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_AttackBossReq_1002001_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_AttackBossResp_1002001_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_AttackBossResp_1002001_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_HurtAwardReq_1002002_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_HurtAwardReq_1002002_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_HurtAwardResp_1002002_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_HurtAwardResp_1002002_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024WorldBossProto.proto\022\nprotoFiles\032\017Role" +
      "Proto.proto\"\027\n\025AttackBossReq_1002001\"6\n\026" +
      "AttackBossResp_1002001\022\016\n\006leftHP\030\001 \001(\003\022\014" +
      "\n\004hurt\030\002 \001(\003\"\026\n\024HurtAwardReq_1002002\"E\n\025" +
      "HurtAwardResp_1002002\022\013\n\003ids\030\001 \003(\005\022\037\n\005it" +
      "ems\030\002 \003(\0132\020.protoFiles.ItemB\027\n\005protoB\016Wo" +
      "rldBossProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoFiles_AttackBossReq_1002001_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoFiles_AttackBossReq_1002001_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_AttackBossReq_1002001_descriptor,
              new java.lang.String[] { });
          internal_static_protoFiles_AttackBossResp_1002001_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protoFiles_AttackBossResp_1002001_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_AttackBossResp_1002001_descriptor,
              new java.lang.String[] { "LeftHP", "Hurt", });
          internal_static_protoFiles_HurtAwardReq_1002002_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protoFiles_HurtAwardReq_1002002_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_HurtAwardReq_1002002_descriptor,
              new java.lang.String[] { });
          internal_static_protoFiles_HurtAwardResp_1002002_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_protoFiles_HurtAwardResp_1002002_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_HurtAwardResp_1002002_descriptor,
              new java.lang.String[] { "Ids", "Items", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.RoleProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
